recipe_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import login_view, logout_view
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'), 
]

recipes/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import create_recipe 
from .views import home, RecipeListView, RecipeDetailView, search_recipes, signup_view, about_view

# This URL configuration is specifically for the 'recipes' app.
# It maps views to specific URL routes so that when a user navigates to a URL, 
# the corresponding view is executed.

app_name = 'recipes'

urlpatterns = [
    # Each path() call maps a URL route to a specific view.
    path('', home, name='home'),
    path('signup/', signup_view, name='signup'),  
    path('about/', about_view, name='about'),
    path('recipes/list/', RecipeListView.as_view(), name='recipe-list'),
    path('recipes/<int:pk>/', RecipeDetailView.as_view(), name='recipe-detail'),
    path('search/', search_recipes, name='search_recipes'),
    path('recipes/create/', create_recipe, name='create-recipe'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/models.py
from django.db import models
from django.core.validators import MinValueValidator

class Recipe(models.Model):
    """
    Represents a culinary recipe containing details about the dish.

    Attributes:
    - name (CharField): The name of the recipe.
    - cooking_time (FloatField): Time (in minutes) needed to prepare the dish.
    - ingredients (CharField): A comma-separated string of ingredients used.
    - description (TextField): A detailed description of the recipe.
    - pic (ImageField): An optional image representing the dish.
    """

    name = models.CharField(max_length=120, unique=True)
    cooking_time = models.FloatField(validators=[MinValueValidator(0.1)])
    ingredients = models.CharField(max_length=350)
    description = models.TextField()
    pic = models.ImageField(upload_to='recipes', default='no_picture.jpg', blank=True, null=True)

    def return_ingredients_as_list(self) -> list:
        """
        Converts the comma-separated string of ingredients into a list.

        Returns:
        - list: A list containing individual ingredients.
        """
        return [ingredient.strip() for ingredient in self.ingredients.split(",")]

    def difficulty(self) -> str:
        """
        Determines the difficulty level of the recipe based on cooking time and ingredient count.

        Difficulty Levels:
        - Easy: Cooking time < 10 mins and less than 4 ingredients.
        - Medium: Cooking time < 10 mins and 4 or more ingredients.
        - Intermediate: Cooking time >= 10 mins and less than 4 ingredients.
        - Hard: Cooking time >= 10 mins and 4 or more ingredients.

        Returns:
        - str: A string representing the difficulty level.
        """
        ingredient_count = len(self.return_ingredients_as_list())
        if self.cooking_time < 10 and ingredient_count < 4:
            return "Easy"
        elif self.cooking_time < 10 and ingredient_count >= 4:
            return "Medium"
        elif self.cooking_time >= 10 and ingredient_count < 4:
            return "Intermediate"
        else:
            return "Hard"

    def __str__(self) -> str:
        """
        String representation of the Recipe model.

        Returns:
        - str: The name of the recipe.
        """
        return str(self.name)

recipes/forms.py
from django import forms
from .models import Recipe
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

CHART_TYPE_CHOICES = [
    ('', 'Select Chart Type'),
    ('#1', 'Bar Chart'),
    ('#2', 'Pie Chart'),
    ('#3', 'Line Chart'),
]

GRAPH_DATA_TYPE_CHOICES = [
    ('cooking_time', 'Cooking Time'),
    ('difficulty', 'Difficulty'),
]


class RecipesSearchForm(forms.Form):
    """
    Form for searching recipes by name or ingredients and 
    selecting the type of chart and data for visualization.
    """
    search = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Search recipes or ingredients', 'class': 'search_input'}),
        help_text='Enter a recipe name or ingredient.'
    )
    chart_type = forms.ChoiceField(
        required=False,
        choices=CHART_TYPE_CHOICES,
        initial='#1',
        widget=forms.Select(attrs={'class': 'chart_type_select'}),
        help_text='Select the type of chart to display.'
    )
    graph_data_type = forms.ChoiceField(
        required=False,
        choices=GRAPH_DATA_TYPE_CHOICES,
        initial='cooking_time',
        widget=forms.Select(attrs={'class': 'graph_data_type_select'}),
        help_text='Select the type of data to plot.'
    )

class RecipeCreateForm(forms.ModelForm):
    """
    Form for creating a new recipe or editing an existing one.
    """
    class Meta:
        model = Recipe
        fields = ['name', 'ingredients', 'cooking_time', 'description', 'pic']
        

class SignUpForm(UserCreationForm):
    """
    Custom sign-up form for user registration.
    Extends Django's default UserCreationForm.
    """
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', )

recipes/views.py
from django.shortcuts import render, redirect     #imported by default
from django.views.generic import ListView, DetailView   #to display lists
from .models import Recipe               #to access recipe model
from .forms import RecipeCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from .forms import UserCreationForm
from django.contrib.auth.forms import UserCreationForm
import pandas as pd
from .utils import get_chart
from django.urls import reverse
from .forms import RecipesSearchForm



class RecipeListView(LoginRequiredMixin, ListView):
    """
    Displays a list of all recipes.
    
    Users must be logged in to access this view.
    """
    model = Recipe
    template_name = 'recipes/recipe_list.html'
    context_object_name = 'recipes'

    def get_context_data(self, **kwargs):
        """
        Overriden to add the search form to the context.
        """
        context = super().get_context_data(**kwargs)
        context['search_form'] = RecipesSearchForm(self.request.GET or None)
        return context

class RecipeDetailView(LoginRequiredMixin,DetailView):
    """
    Displays the detailed view of a single recipe.
    
    Users must be logged in to access this view.
    """
    model = Recipe
    template_name = 'recipes/recipe_detail.html'

def home(request):
    """
    Displays the home page of the application.
    """
    return render(request, 'recipes/home.html')

def about_view(request):
    """
    Displays the about page with information about the project.
    """
    return render(request, 'recipes/about.html')


def search_recipes(request):
    """
    Allows users to search for recipes by name or ingredients.
    Also provides charts for visualizing recipe data.
    """
    is_show_all = request.GET.get('show_all') == 'true'
    default_graph_data_type = 'difficulty' if is_show_all else 'cooking_time'
    graph_data_type = request.GET.get('graph_data_type', default_graph_data_type)
    chart_type = request.GET.get('chart_type', '#1') 
    form = RecipesSearchForm(initial={'graph_data_type': graph_data_type}, data=request.GET or None)
    recipes_df = None
    chart = None
    
    if request.GET.get('show_all') == 'true' or form.is_valid():
        search_term = form.cleaned_data.get('search') if form.is_valid() else None
        if search_term:
            name_matches = Recipe.objects.filter(name__icontains=search_term)
            ingredient_matches = Recipe.objects.filter(ingredients__icontains=search_term)
            queryset = name_matches | ingredient_matches
        else:
            queryset = Recipe.objects.all()
        
        if queryset.exists():
            chart_data_type = request.GET.get('graph_data_type', 'cooking_time')

            data = [
                {
                    'name': f'<a href="{reverse("recipes:recipe-detail", args=[recipe.id])}">{recipe.name}</a>',
                    'cooking_time': recipe.cooking_time,
                    'difficulty': recipe.difficulty(),
                    'ingredients': recipe.ingredients,
                    'description': recipe.description
                }
                for recipe in queryset
            ]
            
            df = pd.DataFrame(data)
            recipes_df = df.to_html(index=False, classes='table table-striped', escape=False)
            
            
        if chart_data_type == 'difficulty':
            difficulty_data = {'Easy': [], 'Medium': [], 'Intermediate': [], 'Hard': []}
            
            for recipe in queryset:
                difficulty_data[recipe.difficulty()].append(recipe.name)
            
            rows = []
            for difficulty, names in difficulty_data.items():
                count = len(names)
                recipe_names = ", ".join(names)
                rows.append({'difficulty': difficulty, 'count': count, 'recipe_names': recipe_names})
                
            difficulty_data_frame = pd.DataFrame(rows)
            chart = get_chart(chart_type, difficulty_data_frame, 'difficulty', queryset)

        elif chart_data_type == 'cooking_time':
            chart = get_chart(chart_type, df, 'cooking_time')

    context = {
        'form': form,
        'recipes_df': recipes_df,
        'chart': chart,
    }
    
    return render(request, 'recipes/search_recipes.html', context)

def create_recipe(request):
    """
    Enables users to create a new recipe.
    
    Supports both GET (displaying the form) and POST (saving the recipe).
    """
    if request.method == 'POST':
        print(request.FILES)
        form = RecipeCreateForm(request.POST, request.FILES)  
        if form.is_valid():
            new_recipe = form.save(commit=False)
            new_recipe.user = request.user
            new_recipe.save()
            return redirect('recipes:recipe-list')
    else:
        form = RecipeCreateForm()
    return render(request, 'recipes/create_recipe.html', {'form': form})


def signup_view(request):
    """
    Allows new users to sign up to the application.
    
    Supports both GET (displaying the signup form) and POST (registering the user).
    """
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('recipes:home')
    else:
        form = UserCreationForm()
    return render(request, 'auth/signup.html', {'form': form})

recipes/templates/recipes/about.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>About</title>
    <link rel="stylesheet" href="{% static 'recipes/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/signup.css' %}"> 
    <link rel="stylesheet" href="{% static 'recipes/css/about.css' %}">

</head>
<body class="kitchen">
    <div class="background-image"></div>
    <div class="content-container">
        <h1>About</h1>
        <div>
        <p>This project aims to build a Django-based web application for recipes, offering features
            like multi-user support and an admin panel. Using Django, which capitalizes on Python's
            strengths, the focus is on creating a state-of-the-art Recipe app that aligns with best
            web development practices. Notable features include deployment on Heroku, Postgres-backed
            data management, an engaging frontend, analytical dashboards, and GitHub integration for
            streamlined code management.</p>

            <p>Check out this project repository: 
                <a href="https://github.com/Gregpk55/Recipe_App" target="_blank" class="link">https://github.com/Gregpk55/Recipe_App</a>
             </p>
             <p>Check out my Portfolio:
                <a href="https://gregpk55.github.io/Portfolio-Webste" target="_blank" class="link">https://gregpk55.github.io/Portfolio-Webste/</a>
             </p>
        </div>
        <div class="button-container">
            {% if user.is_authenticated %}
                <a href="{% url 'recipes:recipe-list' %}" class="btn">View Recipes</a>
                <a href="{% url 'logout' %}" class="btn">Logout</a>
            {% else %}
                <a href="{% url 'recipes:home' %}" class="btn">Home</a>
            {% endif %}
        </div>
        
    </div>
    <script src="{% static 'recipes/js/transition.js' %}"></script>
</body>
</html>

recipes/templates/recipes/create_recipe.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Recipe</title>
    <link rel="stylesheet" href="{% static 'recipes/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/create_recipe.css' %}">
</head>
<body class="cutboard-bg">
    <div class="page-wrapper">
        <div class="background-image"></div>
        <div class="content-container">
          <div class="create-recipe-container">
            <h1>Create Recipe</h1>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <div id="preview" class="preview-image"></div>
              <div>
                <a href="https://www.pexels.com" target="_blank" class="button find_button">Find photos</a>
              </div>
              <button type="submit" class="button" style="background-color: rgb(250, 179, 64);">Create Recipe</button>

          </form>
          
        </div>
        
            <a href="{% url 'recipes:recipe-list' %}" class="btn">Back to Recipe List</a>
        </div>
    </div>
    <script src="{% static 'recipes/js/create_recipe.js' %}"></script>
    <script src="{% static 'recipes/js/transition.js' %}"></script>
</body>
</html>

recipes/templates/recipes/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to My Recipe App</title>
    <link rel="stylesheet" href="{% static 'recipes/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/home.css' %}">
</head>
<body class="kitchen">
    <div class="background-image"></div>
    <div class="content-container">
        <h1>Welcome to my Recipe App</h1>
        <div class="button-container">
            {% if user.is_authenticated %}
                <a href="{% url 'recipes:recipe-list' %}" class="btn">View Recipes</a>
                <a href="{% url 'logout' %}" class="btn">Logout</a>
                <a href="{% url 'recipes:about' %}" class="btn">About</a>
            {% else %}
                <a href="{% url 'login' %}" class="btn">Login</a>
                <a href="{% url 'recipes:signup' %}" class="btn">Create User</a>
                <a href="{% url 'recipes:about' %}" class="btn">About</a>               

            {% endif %}
        </div>
        
    </div>
    <script src="{% static 'recipes/js/transition.js' %}"></script>
</body>
</html>

recipes/templates/recipes/recipe_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object.name }}</title>
    <link rel="stylesheet" href="{% static 'recipes/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/recipe_detail.css' %}">
</head>
<body class="cutboard-bg">
    <div class="page-wrapper">
        <div class="background-image"></div>
        <div class="content-container">
            <div class="recipe-container">
                <img src="{{ object.pic.url }}" alt="{{ object.name }}" class="recipe-image" />
                <div class="recipe-details">
                    <h1>{{ object.name }}</h1>
                    <p><strong>Ingredients:</strong> {{ object.ingredients }}</p>
                    <p><strong>Cooking Time:</strong> {{ object.cooking_time }} minutes</p>
                    <p><strong>Description:</strong> {{ object.description }}</p>
                    <p><strong>Difficulty:</strong> {{ object.difficulty }}</p>
                </div>
            </div>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="btn">Logout</a>
            {% endif %}
            <a href="{% url 'recipes:recipe-list' %}" class="btn">Back to Recipe List</a>
        </div>
    </div>
    <script src="{% static 'recipes/js/transition.js' %}"></script>
</body>
</html>

recipes/templates/recipes/recipe_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recipes List</title>
    <link rel="stylesheet" href="{% static 'recipes/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/recipe_list.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/search.css' %}">
</head>
<body class="cutboard-bg">
    <div class="background-image"></div>
    <div class="content-container">
        <h1>Recipes' List</h1>

         <!-- Search Form -->
         <div class="form-container">
            <form method="get" action="{% url 'recipes:search_recipes' %}">
                <input type="text" name="search" placeholder="Search" value="{{ search_form.data.search }}" class="search_input" />
                <input type="submit" value="Search" class="btn search-btn">
            </form>
        </div>
        
        


        <div class="table-container">
            <div class="recipes-grid">
                {% for recipe in object_list %}
                    <div class="recipe-box">
                        <img src="{{ recipe.pic.url }}" class="recipe-image" />
                        <div class="recipe-name">
                            <a href="{% url 'recipes:recipe-detail' recipe.id %}" class="recipe-link">{{ recipe.name }}</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% if user.is_authenticated %}
        <a href="{% url 'recipes:create-recipe' %}" class="btn">Create Recipe</a>
            <a href="{% url 'logout' %}" class="btn">Logout</a>
        {% endif %}
    </div>
    <script src="{% static 'recipes/js/transition.js' %}"></script>
</body>
</html>

recipes/templates/recipes/search_recipes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search for Recipes</title>
    <link rel="stylesheet" href="{% static 'recipes/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/recipe_list.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/search.css' %}">
</head>
<body class="cutboard-bg">
    <div class="background-image"></div>
    <div class="content-container">
        <h1>Search for Recipes</h1>
        <div class="form-container">
            <form method="GET" action="." class="search-form">
                {{ form.search }}
                {{ form.chart_type }}
                {{ form.graph_data_type }}
                <input type="submit" value="Search" class="btn search-btn">
                <a href="?show_all=true&graph_data_type={{ form.graph_data_type.value }}" class="btn" id="showAllBtn">Show All Recipes</a>
            </form>
        </div>

        <div class="main-container">
    <div class="table-container">
        {% if recipes_df %}
            {{ recipes_df|safe }}
        {% else %}
            <p>No recipes are available.</p>
        {% endif %}
    </div>
    <div class="chart-container">
        {% if chart %}
        

            <img src="data:image/png;base64,{{ chart }}" alt="Chart">
        {% else %}
            <p>No data available to plot the chart.</p>
        {% endif %}
    </div>
    
    <div class="buttons-container">
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" class="btn">Logout</a>
        {% endif %}
        <a href="{% url 'recipes:recipe-list' %}" class="btn">Back to Recipe List</a>
    </div>
</div>
</div>
    <script src="{% static 'recipes/js/transition.js' %}"></script>
</body>
</html>